# Generated by Django 4.1.5 on 2023-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodhaApp', '0002_wt4bhkbookings2_delete_wt4bhkbookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQ3BHKAvailibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MQ4BHKAvailibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WT4BHKAvailibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WT5BHKAvailibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField()),
            ],
        ),
    ]
