# Generated by Django 4.1.5 on 2023-01-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LodhaApp', '0003_mq3bhkavailibility_mq4bhkavailibility_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MQ3BHKAvailibility',
        ),
        migrations.DeleteModel(
            name='MQ4BHKAvailibility',
        ),
        migrations.DeleteModel(
            name='WT4BHKAvailibility',
        ),
        migrations.DeleteModel(
            name='WT5BHKAvailibility',
        ),
    ]
