# Generated by Django 4.1.5 on 2023-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodhaApp', '0004_delete_mq3bhkavailibility_delete_mq4bhkavailibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=100)),
                ('review', models.TextField(max_length=200)),
            ],
        ),
    ]
