# Generated by Django 4.1.5 on 2023-01-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LodhaApp', '0007_wt4bhkpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WT4BHKPayment',
        ),
    ]
